/*Part A:*/
SELECT 
	LGPRODUCT.Prod_SKU,
	LGPRODUCT.Prod_Descript,
	LGPRODUCT.Prod_Type,
	LGPRODUCT.Prod_Price
FROM LGPRODUCT 
	WHERE Prod_Descript IN ( 
		SELECT Prod_Descript
		FROM LGPRODUCT
			Group BY Prod_Descript 
			Having Count(Prod_Type) >1 )
			Order By Prod_Descript;

/*********Part B**/
/*DECLARE the_dpt_num NUMBER(5,0);
BEGIN
  SELECT 
/*SELECT MAX(COUNT(DEPT_NUM)) FROM LGEMPLOYEE GROUP BY DEPT_NUM;*/
/*SELECT DEPT_NUM, COUNT(DEPT_NUM) FROM LGEMPLOYEE GROUP BY DEPT_NUM;*/

/*SELECT DEPT_NUM, COUNT(DEPT_NUM) 
FROM LGEMPLOYEE 
  WHERE COUNT(DEPT_NUM) = (
    SELECT MAX(COUNT(DEPT_NUM)) FROM LGEMPLOYEE
    GROUP BY DEPT_NUM);*/

SELECT
  LGE.EMP_LNAME,
  LGE.EMP_FNAME,
  LGE.EMP_TITLE,
  LGE.DEPT_NUM
FROM LGEMPLOYEE LGE, (
  SELECT DEPT_NUM, COUNT(DEPT_NUM) AS thecount
    FROM LGEMPLOYEE group by DEPT_NUM) deptCounts
    WHERE LGE.DEPT_NUM = deptCounts.DEPT_NUM
    AND deptCounts.thecount = (
      Select MAX(COUNT(DEPT_NUM)) 
      FROM LGEMPLOYEE 
      GROUP BY DEPT_NUM)
      ORDER BY LGE.EMP_LNAME ASC;
      
/********PART C*/
/*
SELECT MAX(LGS.SAL_AMOUNT) FROM LGSALARY_HISTORY LGS, (
  SELECT LGEMPLOYEE.DEPT_NUM FROM LGEMPLOYEE Group by dept_num) theDepts, (
    SELECT LGEMPLOYEE.EMP_NUM FROM LGEMPLOYEE GROUP BY LGEMPLOYEE.EMP_NUM) theEmps
    */
  
/*SELECT DEPT_NUM FROM LGEMPLOYEE GROUP BY DEPT_NUM;
/*8 DEPARTMENTS*/

/*SELECT EMP_NUM, DEPT_NUM FROM LGEMPLOYEE GROUP BY DEPT_NUM, EMP_NUM;*/
/*EVERYONE*/

/*SELECT LGE.DEPT_NUM FROM LGEMPLOYEE LGE, (
  SELECT EMP_NUM FROM LGSALARY_HISTORY) theDeptNum
    WHERE LGE.DEPT_NUM = theDeptNum.DEPT_NUM
    group by LGE.EMP_NUM;

SELECT EMP_NUM FROM LGEMPLOYEE LGE, (
  SELECT DEPT_NUM FROM LGEMPLOYEE GROUP BY DEPT_NUM) eightDepts*/


/*PART D*/

SELECT MAX(PROD_PRICE), BRAND_ID FROM LGPRODUCT GROUP BY BRAND_ID;

SELECT LGP.PROD_SKU FROM LGPRODUCT LGP, (
  SELECT MAX(PROD_PRICE) as theValue, BRAND_ID FROM LGPRODUCT 
    group by BRAND_ID) the_Results
      where LGP.BRAND_ID = the_Results.BRAND_ID 
      and LGP.PROD_PRICE = the_Results.theValue;

/*PART E*/

SELECT 
  LGC.CUST_CODE,
  LGC.CUST_LNAME,
  LGC.CUST_FNAME,
  LGC.CUST_STREET,
  LGC.CUST_STATE,
  LGC.CUST_CITY,
  LGC.CUST_ZIP
FROM LGCUSTOMER LGC 
  WHERE LGC.CUST_BALANCE = 0
UNION 
SELECT 
  LGC.CUST_CODE,
  LGC.CUST_LNAME,
  LGC.CUST_FNAME,
  LGC.CUST_STREET,
  LGC.CUST_STATE,
  LGC.CUST_CITY,
  LGC.CUST_ZIP
FROM LGCUSTOMER LGC 
  WHERE LGC.CUST_BALANCE <> 0;
  
/*PART F*/

/*SELECT 
  LGC.CUST_LNAME,
  LGC.CUST_FNAME,
  LGI.INV_DATE,*/
  

/*part G*/

SELECT TO_CHAR(AVG(SAL_AMOUNT), 'FML99,999.99') AS "Avg Current Salary" FROM LGSALARY_HISTORY WHERE SAL_END IS NULL;

/*PART H*/

/*SELECT AVG(SAL_AMOUNT) FROM LGSALARY_HISTORY WHERE SAL_END IS NULL;
SELECT SAL_AMOUNT FROM LGSALARY_HISTORY WHERE SAL_END IS NULL;

SELECT 
  LGS.EMP_NUM,
  LGE.EMP_LAME,
  LGE.EMP_FNAME,
  LGS.SAL_AMOUNT,
  */